[package]
name = "roblox/roact-compat"
description = "Roact-style API surface implemented on top of React Luau, for easier migration from Roact."
version = "17.3.11"
license = "MIT"
authors = ["Roblox <no-reply@roblox.com>"]
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
repository = "https://github.com/Roblox/react-lua"
exclude = ["rotriever.toml"]

[dependencies]
LuauPolyfill = "roblox/luau-polyfill@^1.2.5"
React = "roblox/react@^17"
ReactGlobals = "roblox/react-globals@^17"
ReactRoblox = "roblox/react-roblox@^17"
Shared = "roblox/react-shared@^17"
