[tools]
wally-package-types = { source = "JohnnyMorganz/wally-package-types", version = "1.6.2" }
stylua = { source = "JohnnyMorganz/StyLua", version = "2.5.2" }
wally = { source = "UpliftGames/wally", version = "0.3.2" }
lute = { source = "luau-lang/lute", version = "=1.0.0" }
rojo = { source = "rojo-rbx/rojo", version = "7.7.0" }
