[package]
name = "stravant/stravant-plugins"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Signal = "stravant/goodsignal@0.3.1"
React = "roblox/react@17.3.11"
ReactRoblox = "roblox/react-roblox@17.3.11"
Roact = "roblox/roact-compat@17.3.11"
Geometry = "stravant/geometry@0.1.3"
createSharedToolbar = "stravant/create-shared-toolbar@0.1.0"
DraggerHandler = "stravant/dragger-handler@0.1.3"
DraggerFramework = "stravant/draggerframework@0.1.4"
DraggerSchemaCore = "stravant/draggerschemacore@0.1.5"
