[package]
name = "stravant/stravant-plugins"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
React = "jsdotlua/react@17.2.1"
ReactRoblox = "jsdotlua/react-roblox@17.2.1"
Roact = "roblox/roact@1.4.4"
RoactCompat = "jsdotlua/roact-compat@17.2.1"
Signal = "stravant/goodsignal@0.3.1"
Geometry = "stravant/geometry@0.1.3"
createSharedToolbar = "stravant/create-shared-toolbar@0.1.0"
DraggerHandler = "stravant/dragger-handler@0.1.3"
DraggerFramework = "stravant/draggerframework@0.1.4"
DraggerSchemaCore = "stravant/draggerschemacore@0.1.5"
