--!strict

local TestTypes = require("./TestTypes")
local Orientation = require("./Orientation")
local ShapeData = require("./ShapeData")
local identifyPart = require("./identifyPart")
local getMeshRepresentation = require("./getMeshRepresentation")

return function(t: TestTypes.TestContext)
	t.test("identifies primitives with identity orientation", function()
		local wedge = Instance.new("WedgePart")
		wedge.Size = Vector3.new(2, 3, 4)
		wedge.CFrame = CFrame.new(1, 2, 3) * CFrame.Angles(0.5, 0, 0)
		local state = identifyPart(wedge)
		assert(state, "expected a state")
		t.expect(state.Shape).toBe("Wedge")
		t.expect(state.Orientation).toBe(Orientation.Identity)
		t.expect(state.IsMeshRepresentation).toBeFalsy()
		t.expect(state.PrimitiveOnly).toBeFalsy()
		t.expect((state.ShapeSize - Vector3.new(2, 3, 4)).Magnitude < 0.001).toBeTruthy()
		wedge:Destroy()
	end)

	t.test("identifies published mesh representations by MeshId", function()
		local classId = ShapeData.classRepOf("Wedge",
			Orientation.quarterTurnAbout(Enum.NormalId.Right, true))
		local meshPart = getMeshRepresentation("Wedge", classId)
		meshPart.Size = Orientation.permuteSize(Orientation.invert(classId), Vector3.new(2, 3, 4))
		meshPart.CFrame = CFrame.new(5, 6, 7) * Orientation.getCFrame(classId)

		local state = identifyPart(meshPart)
		assert(state, "expected a state")
		t.expect(state.Shape).toBe("Wedge")
		t.expect(state.Orientation).toBe(classId)
		t.expect(state.IsMeshRepresentation).toBeTruthy()
		t.expect((state.ShapeSize - Vector3.new(2, 3, 4)).Magnitude < 0.001).toBeTruthy()
		t.expect((state.ShapeCFrame.Position - Vector3.new(5, 6, 7)).Magnitude < 0.001).toBeTruthy()
		t.expect((state.ShapeCFrame.XVector - Vector3.xAxis).Magnitude < 0.001).toBeTruthy()

		meshPart:Destroy()
	end)

	t.test("flags SpecialMesh parts as primitive only", function()
		local part = Instance.new("Part")
		local mesh = Instance.new("SpecialMesh")
		mesh.MeshType = Enum.MeshType.Wedge
		mesh.Parent = part
		local state = identifyPart(part)
		assert(state)
		t.expect(state.Shape).toBe("Wedge")
		t.expect(state.PrimitiveOnly).toBeTruthy()
		part:Destroy()
	end)

	t.test("treats foreign mesh parts as approximated boxes", function()
		local foreign = Instance.new("MeshPart")
		local state = identifyPart(foreign)
		assert(state, "expected a state")
		t.expect(state.Shape).toBe("Brick")
		t.expect(state.ApproximatedAsBox).toBeTruthy()
		t.expect(state.PrimitiveOnly).toBeTruthy()
		t.expect(state.IsMeshRepresentation).toBeFalsy()
		foreign:Destroy()
	end)

	t.test("primitives are not approximated", function()
		local part = Instance.new("Part")
		local state = identifyPart(part)
		assert(state)
		t.expect(state.ApproximatedAsBox).toBeFalsy()
		part:Destroy()
	end)

	t.test("rejects terrain", function()
		t.expect(identifyPart(workspace.Terrain)).toBe(nil)
	end)
end
