[package]
name = "roblox/safe-flags"
description = "SafeFlags makes it possible to use the internal flagging API in all Script contexts. The main use case is to allow our public packages to be flagged while also safe to consumer in user-level Scripts."
version = "0.1.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"
authors = ["Roblox <no-reply@roblox.com>"]
# repository = "https://github.com/Roblox/safe-flags" no public repo
exclude = [
    "Packages",
    "default.rbxp",
    "foreman.toml",
    "lest.log",
    "multipack.toml",
    "rotriever.lock",
    "rotriever.toml",
    "selene-requires.yml",
    "selene.toml",
    "suites",
    "src/**/*.test.lua",
]

[dependencies]
