[package]
name = "roblox/react-shared"
description = "Internal shared utilities used across React Luau packages."
version = "17.3.11"
license = "MIT"
authors = ["Roblox <no-reply@roblox.com>"]
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
repository = "https://github.com/Roblox/react-lua"
exclude = ["rotriever.toml"]

[dependencies]
LuauPolyfill = "roblox/luau-polyfill@^1.2.5"
SafeFlags = "roblox/safe-flags@^0.1.2"
ReactGlobals = "roblox/react-globals@^17"
