[package]
name = "roblox/react"
description = "A translation of React 17 into Luau, tuned for Roblox."
version = "17.3.11"
license = "MIT"
authors = ["Roblox <no-reply@roblox.com>"]
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
repository = "https://github.com/Roblox/react-lua"
exclude = ["rotriever.toml"]

[dependencies]
LuauPolyfill = "roblox/luau-polyfill@^1.2.5"
ReactGlobals = "roblox/react-globals@^17"
Shared = "roblox/react-shared@^17"
