name: Publish

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Foreman
        uses: Roblox/setup-foreman@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          allow-external-github-orgs: true

      - name: Publish released plugin to Creator Store
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ROBLOX_API_KEY: ${{ secrets.ROBLOX_API_KEY }}
          TAG: ${{ github.event.release.tag_name }}
        run: lute scripts/publishToCreatorStore.luau
