name: Release

on:
  push:
    tags: ["v*"]

permissions:
  contents: write

jobs:
  draft-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Foreman
        uses: Roblox/setup-foreman@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          allow-external-github-orgs: true

      - name: Install Wally packages
        run: wally install

      - name: Create draft release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ github.ref_name }}
        run: lute scripts/createReleases.luau
