name: Release

on:
  push:
    tags: ["v*"]

permissions:
  contents: write

jobs:
  draft-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rokit
        uses: CompeyDev/setup-rokit@v0.1.2
        with:
          token: ${{ github.token }}
          cache: true

      - name: Install Wally packages
        run: wally install

      - name: Build plugins
        run: lute scripts/build.luau all --out build

      - name: Create draft release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: build/*
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
