name: Test

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: luau-execution-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Foreman
        uses: Roblox/setup-foreman@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          allow-external-github-orgs: true

      - name: Install Wally packages
        run: wally install

      - name: Run tests
        env:
          ROBLOX_API_KEY: ${{ secrets.ROBLOX_API_KEY }}
          ROBLOX_UNIVERSE_ID: ${{ vars.ROBLOX_TEST_UNIVERSE_ID }}
          ROBLOX_PLACE_ID: ${{ vars.ROBLOX_TEST_PLACE_ID }}
          TEST_UNIVERSE_ID: ${{ vars.ROBLOX_TEST_UNIVERSE_ID }}
          TEST_PLACE_ID: ${{ vars.ROBLOX_TEST_PLACE_ID }}
        run: lute run scripts/test all
